name: sats_app
description: "Sats App -- The easiest-to-use Bitcoin wallet."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  api_client:
    path: ./api_client
  cdk_flutter:
    git:
      url: https://github.com/davidcaseria/cdk_flutter.git
  amplify_auth_cognito: ^2.0.0
  amplify_flutter: ^2.0.0
  animated_digit: ^3.2.3
  app_links: ^6.4.0
  bip39: ^1.0.6
  bloc: ^9.0.0
  chopper: ^8.0.0
  cryptography: ^2.7.0
  cupertino_icons: ^1.0.6
  dio: ^5.8.0+1
  equatable: ^2.0.7
  file_picker: ^10.2.0
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^9.2.4
  flutter_sticky_header: ^0.8.0
  intl: ^0.20.2
  json_annotation: ^4.8.0
  local_auth: ^2.3.0
  local_session_timeout: ^3.2.0
  mobile_scanner: ^7.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  pinput: ^5.0.1
  qr_flutter: ^4.1.0
  searchable_listview: ^2.19.0
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  chopper_generator: ^8.0.0
  json_serializable: ^6.6.1
  swagger_dart_code_generator: ^3.0.1

flutter:
  uses-material-design: true
